### PR TITLE
feat: Upgrade dependencies. Bump version

### PR DESCRIPTION
**Pull request by khorolets**

### CODE REVIEW

**Review by frol — APPROVED** [review]

**Comment by khorolets** [comment]
@chefsale could you clarify if I can merge it with FOSA fails in buildkite?

**Comment by chefsale** [comment]
Restarted the job now, lets see.

**Comment by frol** [comment]
@chefsale re-run did not help

**Comment by chefsale** [comment]
@frol @khorolets  yes, I fixed it now. There was a mis-configuration when I was doing some changes.

**Pull request merged**
